### ISSUE TITLE
Time for doing guys . _ .

### ISSUE THREAD

**Issue by NguyenTanPhat10a13pn** [nhom7PN/Nhom-7-C13#12]
Vô đây làm nào Bài 9 câu 1 ai cũng phải làm 1 cái nha (～￣▽￣)～

**Comment by nguyenminhduc10a13PN** [comment]
hahahaahahahahahaahahahahaah

**Comment by NguyenTanPhat10a13pn** [comment]
alô @NguyenXuanPhong10a13pn @NguyenTuanHuy10a13pn @Daoanhthu2711 @nguyenminhduc10a13PN 
Điểm danh có mặt để chia việc làm nào

**Comment by Daoanhthu2711** [comment]
bt rùiiii

**Comment by NguyenXuanPhong10a13pn** [comment]
Oki

**Comment by NguyenTuanHuy10a13pn** [comment]
Rõ rồi ông =))

**Comment by NguyenTanPhat10a13pn** [comment]
đầy đủ r nha giờ chia việc
mỗi người làm 1 câu nhưng câu 1 bài 9 tất cả đều làm nha

**Comment by NguyenTuanHuy10a13pn** [comment]
Mình xí câu 1 bài 10

**Comment by NguyenTuanHuy10a13pn** [comment]
@NguyenTanPhat10a13pn tôi xong rồi nha ông
