### ISSUE TITLE
Lẹt gâu fỏ a 2nd sếmtẻ 

### ISSUE THREAD

**Issue by NguyenTanPhat10a13pn** [nhom7PN/Nhom-7-C13#13]

**Comment by NguyenTanPhat10a13pn** [comment]
@NguyenXuanPhong10a13pn @nguyenminhduc10a13PN @NguyenTuanHuy10a13pn @Daoanhthu2711 wake ur ass up and chat pls

**Comment by nguyenminhduc10a13PN** [comment]
ok im here

**Comment by nguyenminhduc10a13PN** [comment]
hows ur ?

**Comment by Daoanhthu2711** [comment]
Hi

**Comment by NguyenTuanHuy10a13pn** [comment]
Quên mk github các bạn ơi =))

**Comment by NguyenTanPhat10a13pn** [comment]
> Quên mk github các bạn ơi =))
ao chinh`

**Comment by NguyenTuanHuy10a13pn** [comment]
Các bạn à

**Comment by NguyenTuanHuy10a13pn** [comment]
Ngày nghỉ là khái niệm xa xỉ lắm, mình phải chạy deadline mới đúng

**Comment by nguyenminhduc10a13PN** [comment]
này mng

**Comment by nguyenminhduc10a13PN** [comment]
tuần sau nhóm mình làm bài tin nha

**Comment by nguyenminhduc10a13PN** [comment]
@NguyenTanPhat10a13pn @NguyenTuanHuy10a13pn @Daoanhthu2711 @NguyenXuanPhong10a13pn

**Comment by Daoanhthu2711** [comment]
Okee

**Comment by NguyenTanPhat10a13pn** [comment]
Làm gì

**Comment by NguyenTuanHuy10a13pn** [comment]
Ủa Phát chưa xem à ._.

**Comment by NguyenTuanHuy10a13pn** [comment]
Làm sớm khoẻ thôi, tuần sau kt các kiểu nữa

**Comment by NguyenTanPhat10a13pn** [comment]
phân công eyyyy

**Comment by NguyenTanPhat10a13pn** [comment]
@nguyenminhduc10a13PN @NguyenTanPhat10a13pn @NguyenTuanHuy10a13pn @Daoanhthu2711 @NguyenXuanPhong10a13pn vào phần projects tự tạo column việc làm đi :Đ

**Comment by NguyenTuanHuy10a13pn** [comment]
Phong đâu?

**Comment by NguyenTanPhat10a13pn** [comment]
t biết t phải làm word nên kác pạn tự chia việc nha :Đ

**Comment by nguyenminhduc10a13PN** [comment]
chia việc nha

**Comment by NguyenXuanPhong10a13pn** [comment]
oki chia đi bạn êi

**Comment by NguyenXuanPhong10a13pn** [comment]
nhanh còn làm Hoá nx

**Comment by HienCaoPhuNhuan** [comment]
@NguyenTanPhat10a13pn kêu ghi tên Tuần 1 mà ghi Tuần 4 là như nào con

**Comment by NguyenTanPhat10a13pn** [comment]
> @NguyenTanPhat10a13pn kêu ghi tên Tuần 1 mà ghi Tuần 4 là như nào con

em tưởng ghi theo tuần học :(

**Comment by nguyenminhduc10a13PN** [comment]
hé lô mng

**Comment by nguyenminhduc10a13PN** [comment]
tối nay mình làm tin nha

**Comment by nguyenminhduc10a13PN** [comment]
giờ  phân công thế này

**Comment by nguyenminhduc10a13PN** [comment]
Thư với Huy sẽ phụ trách việc tìm thông tin, với thông tin sẽ là một câu ca dao tục ngữ nào đó và sẽ gửi cho Phát bên mảng word

**Comment by NguyenTuanHuy10a13pn** [comment]
Đang nghe đây nhóm trưởng =))

**Comment by NguyenTuanHuy10a13pn** [comment]
Ủa

**Comment by NguyenTuanHuy10a13pn** [comment]
Ca dao tục ngữ thôi hả

**Comment by nguyenminhduc10a13PN** [comment]
phong với Đức là t sẽ tìm những tinh hoa phú quý của văn chương, ý là đi tìm các lý lẽ và dẫn chứng đó =))) nói thế cho nó ra dáng văn vẻ hiếu học thế thôi=))), sau đó Phát sẽ làm phần công việc còn lại và viết báo cáo

**Comment by nguyenminhduc10a13PN** [comment]
oke nha

**Comment by nguyenminhduc10a13PN** [comment]
gudluck

**Comment by nguyenminhduc10a13PN** [comment]
see you all

**Comment by nguyenminhduc10a13PN** [comment]
@NguyenXuanPhong10a13pn @NguyenTanPhat10a13pn @NguyenTuanHuy10a13pn @Daoanhthu2711

**Comment by nguyenminhduc10a13PN** [comment]
hỡi các bạn

**Comment by nguyenminhduc10a13PN** [comment]
sao mình mod xong con phím r mà các bạn vẫn chưa hiện lên z

**Comment by nguyenminhduc10a13PN** [comment]
hãy thức tỉnh đi nào

**Comment by nguyenminhduc10a13PN** [comment]
=)))))) alooooooooooooooooo

**Comment by Daoanhthu2711** [comment]
Bìn tĩn

**Comment by nguyenminhduc10a13PN** [comment]
deadline sát đít kêu bình tĩnh =)?

**Comment by nguyenminhduc10a13PN** [comment]
bây giờ t cần 3 câu ca dao tục ngữ

**Comment by nguyenminhduc10a13PN** [comment]
nghị luận về cuộc sống xung quanh mà bản thân cảm nhận được

**Comment by nguyenminhduc10a13PN** [comment]
không thì bây giờ nè, Phát sẽ làm cái cover page

**Comment by nguyenminhduc10a13PN** [comment]
Phong Thư với Huy sẽ kiếm nội dung

**Comment by nguyenminhduc10a13PN** [comment]
t thì làm các phần còn lại
