### ISSUE TITLE
Nộp những thứ chuẩn bị ở tuần 2 <3

### ISSUE THREAD

**Issue by NguyenTanPhat10a13pn** [nhom7PN/Nhom-7-C13#16]
### Discussed in https://github.com/nhom7PN/Nhom-7-C13/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **nguyenminhduc10a13PN** February 24, 2022</sup>
làm bài làm bài êyyyyy</div>

**Comment by NguyenTuanHuy10a13pn** [comment]
Tưởng tuần trước nộp rồi luôn ấy ._.

**Comment by NguyenTanPhat10a13pn** [comment]
where  ?

**Comment by NguyenTanPhat10a13pn** [comment]
> Tưởng tuần trước nộp rồi luôn ấy ._.

Lmao whẻe

**Comment by NguyenTuanHuy10a13pn** [comment]
Chắc t bị ngáo =))

**Comment by NguyenTuanHuy10a13pn** [comment]
Có câu tích đức tu nhân,
Hoạn nạn tương cứu, phú bần tương tri.
Cây xanh thời (thì) lá cũng xanh,
Cha mẹ hiền lành để đức cho con.

**Comment by Daoanhthu2711** [comment]
Lá lành đùm lá rách, lá rách ít đùm lá rách nhiều.
Mừng cây rồi lại mừng cành, 
Cây đức lắm chồi, người đức lắm con.

**Comment by NguyenTanPhat10a13pn** [comment]
O`

**Comment by NguyenTanPhat10a13pn** [comment]
ey xin cre mấy câu ở trên được ko @NguyenTuanHuy10a13pn @Daoanhthu2711
