### ISSUE TITLE
Dậy và làm bài nào các bạn

### ISSUE THREAD

**Issue by NguyenTanPhat10a13pn** [nhom7PN/Nhom-7-C13#17]
@nguyenminhduc10a13PN @NguyenTuanHuy10a13pn @Daoanhthu2711 @NguyenXuanPhong10a13pn

**Comment by NguyenTanPhat10a13pn** [comment]
pà @NguyenTuanHuy10a13pn phân tích 2 câu tích đức gì đó đi pà

**Comment by NguyenTanPhat10a13pn** [comment]
gửi vào đây đi pà @NguyenTuanHuy10a13pn

**Comment by NguyenTuanHuy10a13pn** [comment]
T làm văn hơi đụt, có gì các bạn chỉnh sửa nha

**Comment by NguyenTuanHuy10a13pn** [comment]
Tích đức: quan niệm xưa của cha ông về việc sống, dạy con người phải sống với cái tâm thiện, làm việc thiện để tích công đức, phước lành
Tu nhân đi kèm với tích đức, vừa tích đức vừa cải thiện bản thân, điều chỉnh lối sống, lối tư duy
 Thấy người gặp hoạn nạn thì giúp đỡ, có là tu nhân, cũng là tích đức.
Cuộc sống cũng như thế, có tích đức, tu nhân, có lòng nhân ái thì con người mới phát triển,...

**Comment by NguyenTanPhat10a13pn** [comment]
không sao pà tôi cũng thieunang ngôn ngữ tiếng Việt

**Comment by NguyenTuanHuy10a13pn** [comment]
Nói thế thầy đánh giá

**Comment by NguyenTanPhat10a13pn** [comment]
> Tích đức: quan niệm xưa của cha ông về việc sống, dạy con người phải sống với cái tâm thiện, làm việc thiện để tích công đức, phước lành Tu nhân đi kèm với tích đức, vừa tích đức vừa cải thiện bản thân, điều chỉnh lối sống, lối tư duy Thấy người gặp hoạn nạn thì giúp đỡ, có là tu nhân, cũng là tích đức. Cuộc sống cũng như thế, có tích đức, tu nhân, có lòng nhân ái thì con người mới phát triển,...

vjp wa'

**Comment by NguyenTuanHuy10a13pn** [comment]
Sống dậy đi =))
